# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df0eeeeba2124f280359ddf47ef6a5abde93306073ff783c4cf39a2008811251eac1b7b3a0175dcd3bb8a7554d36c77ba024d5b2d0e004b18dcec21bb182ea68

test:
  secret_key_base: 93b4c724761d2973cdacaa01574569afdfa3967b36db91e430cde5c92a0ef490fd8ef375dcbfec6309ad8b82116c5123ce54a601855e967dd3a8b03b41a37cf7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
